// <auto-generated />
namespace LTQL_1721050358.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Creae_table_THQSinhVen358 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creae_table_THQSinhVen358));
        
        string IMigrationMetadata.Id
        {
            get { return "202112250141354_Creae_table_THQSinhVen358"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
